#!/bin/bash
if [ ! -d "bin/" ]
then
    mkdir bin
fi

clang++ -std=c++20 -g -iquote"src" -L"lib" -I"include" src/main.cpp src/gfx/window.cpp src/gfx/instance.cpp src/gfx/physical_device.cpp src/gfx/logical_device.cpp src/gfx/window_surface.cpp -o bin/application -lvulkan -lglfw3
