#!/bin/bash
if [ ! -d "bin/" ]
then
    mkdir bin
fi

glslc res/shaders/core.vert -o bin/shaders/coreVert.spv
glslc res/shaders/core.frag -o bin/shaders/coreFrag.spv

clang++ -std=c++20 -g -iquote"src" -L"lib" -I"include" src/main.cpp src/gfx/window.cpp src/gfx/instance.cpp src/gfx/physical_device.cpp src/gfx/logical_device.cpp src/gfx/window_surface.cpp src/gfx/swapchain.cpp src/gfx/pipeline.cpp src/gfx/render_pass.cpp -o bin/application -lvulkan -lglfw3
